{% set version = "2.3.8" %}
{% set sha256 = "ef0ddd04f9d56b654dc54bd82514f852cc188bb3cda6b0845b6120dc385fe912" %}

package:
  name: orthofinder
  version: {{ version }}

build:
  noarch: True
  number: 1

source:
  url: https://github.com/davidemms/OrthoFinder/releases/download/{{ version }}/OrthoFinder-{{ version }}_source.tar.gz
  sha256: {{ sha256 }}

requirements:
  run:
    - python=2.7
    - scipy
    - blast
    - diamond
    - mcl
    - fastme
    - dlcpar
    - mafft
    - fasttree
    - muscle
    - raxml
    - iqtree
    - bzip2
    - mmseqs2

test:
  commands:
    - orthofinder > /dev/null

about:
  home: https://github.com/davidemms/OrthoFinder
  summary: Accurate inference of orthogroups, orthologues, gene trees and rooted species tree made easy!
  license: GPLv3
  license_file: orthofinder/License.md
